baseURL = "/"
title = "Modnar Musings"
theme = "HugoRelearn"
themesDir = "themes"
languageCode = "en-us"
canonifyURLs = true
relativeURLs = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
  [[menu.addendum]]
    identifier = 'addendum-top'
    name = 'A Menu Title for the Whole Menu'

  [[menu.addendum]]
    name = 'A Menu Entry Title for Child 1'
    parent = 'addendum-top'
    url = 'https://example.com/1'
    weight = 1

  [[menu.addendum]]
    name = 'A Menu Entry Title for Child 2'
    parent = 'addendum-top'
    url = 'https://example.com/2'
    weight = 2

[params]
  disableLandingPageButton = false
  landingPageName = '<i class="fa-fw fas fa-anchor"></i>'